# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM node:18 as build-stage

WORKDIR /app

COPY package*.json /app/

RUN npm install

COPY ./ /app/

ARG FRONTEND_ENV=production

ENV REACT_APP_ENV=${FRONTEND_ENV}

# Comment out the next line to disable tests
RUN #npm run test-once

RUN npm run build


# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.23

COPY --from=build-stage /app/build/ /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx/nginx-backend-not-found.conf /etc/nginx/extra-conf.d/backend-not-found.conf